node {
stage('SCM checkout'){
git 'https://github.com/suriya8187/git-java-maven'
}
stage('compile package'){
def mvnHome=tool name: 'AWSMaven', type: 'maven'
  sh "${mvnHome}/bin/mvn -f Helloworld/pom.xml package"
}
}
